config/routes.rb
Rails.application.routes.draw do
  resources :incidents

  root 'static_pages#home'
  get 'help' => 'static_pages#help'
  get 'about' => 'static_pages#about'
  get 'contact' => 'static_pages#contact'

end

app/models/incident.rb
class Incident < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/incidents_controller.rb
class IncidentsController < ApplicationController
  before_action :set_incident, only: [:show, :edit, :update, :destroy]

  # GET /incidents
  # GET /incidents.json
  def index
    @incidents = Incident.all
  end

  # GET /incidents/1
  # GET /incidents/1.json
  def show
  end

  # GET /incidents/new
  def new
    @incident = Incident.new
  end

  # GET /incidents/1/edit
  def edit
  end

  # POST /incidents
  # POST /incidents.json
  def create
    @incident = Incident.new(incident_params)

    respond_to do |format|
      if @incident.save
        format.html { redirect_to @incident, notice: 'Incident was successfully created.' }
        format.json { render :show, status: :created, location: @incident }
      else
        format.html { render :new }
        format.json { render json: @incident.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /incidents/1
  # PATCH/PUT /incidents/1.json
  def update
    respond_to do |format|
      if @incident.update(incident_params)
        format.html { redirect_to @incident, notice: 'Incident was successfully updated.' }
        format.json { render :show, status: :ok, location: @incident }
      else
        format.html { render :edit }
        format.json { render json: @incident.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /incidents/1
  # DELETE /incidents/1.json
  def destroy
    @incident.destroy
    respond_to do |format|
      format.html { redirect_to incidents_url, notice: 'Incident was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_incident
      @incident = Incident.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def incident_params
      params.require(:incident).permit(:issue, :env, :region, :description, :rootcause, :resolution, :status)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end

  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/incidents_helper.rb
module IncidentsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/incidents/_form.html.erb
<%= form_for(@incident) do |f| %>
  <% if @incident.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@incident.errors.count, "error") %> prohibited this incident from being saved:</h2>

      <ul>
      <% @incident.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :issue %><br>
    <%= f.text_field :issue %>
  </div>
  <div class="field">
    <%= f.label :env %><br>
    <%= f.text_field :env %>
  </div>
  <div class="field">
    <%= f.label :region %><br>
    <%= f.text_field :region %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
    <div class="field">
      <%= f.label :status %><br>
      <%= f.text_field :status %>
    </div>
  <div class="field">
    <%= f.label :rootcause %><br>
    <%= f.text_area :rootcause %>
  </div>
  <div class="field">
    <%= f.label :resolution %><br>
    <%= f.text_area :resolution %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/incidents/edit.html.erb
<h1>Editing Incident</h1>

<%= render 'form' %>

<%= link_to 'Show', @incident %> |
<%= link_to 'Back', incidents_path %>

app/views/incidents/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Incidents</h1>
<div class="container">
  <span class="btn btn-info btn-sm"> <%= link_to '+New Incident', new_incident_path %></span> <br /><br />
  <table class="table table-bordered table-hover" >
  <thead>
    <tr>
      <th>Issue</th>
      <th>Env</th>
      <th>Region</th>
      <th>Description</th>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @incidents.each do |incident| %>
      <tr>
        <td><%= incident.issue %></td>
        <td><%= incident.env %></td>
        <td><%= incident.region %></td>
        <td><%= incident.description %></td>
        <td><%= incident.status %></td>
        <td><%= link_to 'Show', incident %></td>
        <td><%= link_to 'Edit', edit_incident_path(incident) %></td>
        <td><%= link_to 'Destroy', incident, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
<br>

app/views/incidents/new.html.erb
<h1>New Incident</h1>

<%= render 'form' %>

<%= link_to 'Back', incidents_path %>

app/views/incidents/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Issue:</strong>
  <%= @incident.issue %>
</p>

<p>
  <strong>Env:</strong>
  <%= @incident.env %>
</p>

<p>
  <strong>Region:</strong>
  <%= @incident.region %>
</p>

<p>
  <strong>Description:</strong>
  <%= @incident.description %>
</p>
<p>
  <strong>Status:</strong>
  <%= @incident.status %>
</p>
<p>
  <strong>Rootcause:</strong>
  <%= @incident.rootcause %>
</p>

<p>
  <strong>Resolution:</strong>
  <%= @incident.resolution %>
</p>

<%= link_to 'Edit', edit_incident_path(@incident) %> |
<%= link_to 'Back', incidents_path %>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <a href="#">Incidents Management</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "Incident Management", '#', id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home",   root_path %></li>
        <li><%= link_to "Help",   help_path %></li>
        <li><%= link_to "Log in", '#' %></li>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RailsIncidents</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>
<body>
 <%= render 'layouts/header' %>
    <div class="container">
      <%= yield %>
    </div>
<%= render 'layouts/footer' %>
</body>
</html>

app/views/static_pages/about.html.erb
<h1>StaticPages#about</h1>
<p>Find me in app/views/static_pages/about.html.erb</p>

app/views/static_pages/contact.html.erb
<h1>StaticPages#contact</h1>
<p>Find me in app/views/static_pages/contact.html.erb</p>

app/views/static_pages/help.html.erb
<h1>StaticPages#help</h1>
<p>Find me in app/views/static_pages/help.html.erb</p>

app/views/static_pages/home.html.erb
<h1>StaticPages#home</h1>
<p>Find me in app/views/static_pages/home.html.erb</p>